### ISSUE TITLE
error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by jason2li** [Pilloxa/react-native-nordic-dfu#10]
I'm am trying to get this up and running, but once I install this plugin, I can no longer run the application.  I get the following error:

```
node_modules\react-native-nordic-dfu\android\src\main\java\com\pilloxa\dfu\RNNordicDfuPackage.java:19: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-nordic-dfu:compileReleaseJavaWithJavac FAILED
```

I am working in Windows 10 and testing on Android (IOS will be next).

**Comment by vikeri** [comment]
This is probably an issue with version of RN greater than 0.47, this is the fix that was done in another library: https://github.com/vikeri/react-native-background-job/pull/46/files

I'll try to deploy it ASAP

**Comment by vikeri** [comment]
If anyone wants to test it and then submit a PR I'd happily merge it 👍

**Comment by dariuszseweryn** [comment]
Does any of the above PRs qualify for merging?
