### ISSUE TITLE
Getting Swift._ArrayBuffer._copyContent error with v3.2.0

### ISSUE THREAD

**Issue by juanpaternina** [Pilloxa/react-native-nordic-dfu#137]
Hi. 

I'm trying to compile last version and I'm getting an swift Error.

**My procedure.**
npx react-native init LiftDFU
yarn add react-native-nordic-dfu
npx pod-install
npx react-native run-los

**my current Stack** 

`System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
    Memory: 20.55 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v12.21.0/bin/npm
    Watchman: 4.9.0 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 23, 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.2 AI-202.7660.26.42.7322048
    Xcode: 12.5/12E262 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1
    react-native: 0.64.1 => 0.64.1
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found`

**Screenshoots**
<img width="1440" alt="Screen Shot 2021-05-17 at 10 19 46 AM" src="https://user-images.githubusercontent.com/21976360/118514077-de712100-b6f9-11eb-85c5-260d651e9f80.png">

**Comment by cheehieu** [comment]
@juanpaternina I am seeing a similar build error. Were you able to fix it?
