### ISSUE TITLE
Error Code code":"4097" Dfu process failed(Android)

### ISSUE THREAD

**Issue by ChandraIOT** [Pilloxa/react-native-nordic-dfu#14]
When we are trying to fo Dfu of the device Below message is coming on console.

{"framesToPop":1,"code":"4097"}

Please suggest what can be the issue

**Comment by vikeri** [comment]
I have never seen that issue, can you check if it is reported in the parent project here: https://github.com/NordicSemiconductor/Android-DFU-Library

**Comment by ChandraIOT** [comment]
It was a file path issue, it corrected when we specify correct path to firmware file. 

Closing this issue now.
