### ISSUE TITLE
iOS runtime error convert to NSString

### ISSUE THREAD

**Issue by j-sanders123** [Pilloxa/react-native-nordic-dfu#22]
Error shows up in example app when Start Dfu button is pressed. If anyone had a similar problem or knows what my error could be let me know! Thanks in advance.

JSON value '0' of type NSNumber cannot be converted to NSString

Error screens attached. 
![img_0859](https://user-images.githubusercontent.com/17932078/41786475-9912d358-7613-11e8-8ffd-77d8e2f772d3.jpeg)
![img_0860](https://user-images.githubusercontent.com/17932078/41786478-9b83b01c-7613-11e8-9fc7-19c74dabda9b.jpeg)

**Comment by vikeri** [comment]
@j-sanders123 Are you still experiencing this issue?
