### ISSUE TITLE
[IOS only] react-native-ble-manager error after update firmware

### ISSUE THREAD

**Issue by VitamineC** [Pilloxa/react-native-nordic-dfu#48]
Hi everyone,
After success update firmware something happens with react-native-ble-manager. I can't scan perf, can't connect\disconnect devices. Only restart application help me.

Some additionally:
I try debug IOS part of library, 
as for me problem inside iOSDFULibrary.framework, because I remove step by step some code part from wrapper and can't doing anything with this problem

**Comment by fundlg** [comment]
+1

**Comment by VitamineC** [comment]
I resolve this problem. It's not the best solutions, however this help me.

[IOS only]

1. After success update you should reinit bleManager, because iOSDFULibrary.framework kill its instance. 
2. When you try reinit manager (call start method) you will get error about duplication when you will try to connect devices.  I resolve this problem in my fork. 
https://github.com/VitamineC/react-native-ble-manager
3. After success reinit you should reconnect All(!) devices, and resubscribe all notify.

That's all.
