### ISSUE TITLE
Could not find method google() for arguments [] on repository container

### ISSUE THREAD

**Issue by shayhz** [Pilloxa/react-native-nordic-dfu#55]
Hi,

I installed the package for android according to instructions.
When running "react-native run android" I get the following error:
"Could not find method google() for arguments [] on repository container".
I don't understand why...
My RN version is 0.50.3.
I compared gradle configuration to the example project and everything is the same.
Any clue why I receive this error?
Thanks,

**Comment by Looveh** [comment]
Are you sure this is related to this library? This is an issue we've never encountered before

**Comment by Looveh** [comment]
@shayhz Closing this for now, please re open when you suspect this library might be the culprit
