### ISSUE TITLE
support iOS DFU property

### ISSUE THREAD

**Issue by heyupeng** [Pilloxa/react-native-nordic-dfu#65]
On swift, I can set some properties in DFUServiceInitiator class, but on RN, I can not do any property setting. I hope you can add some bridges to do it.

**Comment by Looveh** [comment]
@heyupeng It's not a feature we'll be able to allocate time to implement any time soon, however if it's something you need we do accept PR's

**Comment by heyupeng** [comment]
Okay, thanks in advance!

**Comment by Looveh** [comment]
Great, PR's are always welcome 😊
