### ISSUE TITLE
Not able to run -  sd_ble_gatts_service_changed() 

### ISSUE THREAD

**Issue by vivekspraxa** [Pilloxa/react-native-nordic-dfu#76]
For dfu to show device i need to run  
sd_ble_gatts_service_changed() to the BLE_GAP_EVT_CONNECTED case in ble_evt_handler() in main.c.

Do you have any example for it as on my device it is getting cached and failing the dfu process

https://devzone.nordicsemi.com/f/nordic-q-a/50272/ios-nrfconnect-issue-with-dfu

**Comment by Looveh** [comment]
We're unfortunately unable to debug or provide examples of how the firmware should be implemented within the scope of this project
