### ISSUE TITLE
IOS DFU State: DFU_FAILED Error: DFU Service not found

### ISSUE THREAD

**Issue by gaoyang189** [Pilloxa/react-native-nordic-dfu#98]
While doing
NordicDFU.startDFU({
            deviceAddress: this.state.deviceUUID,
            deviceName: "Secure_nRF51",
            filePath: url,
})
Causing error "DFU Service not found"
When executing on Android, changing the UUID to MAC can be performed normally, but an Error: DFU Service not found will appear on IOS.Please help me sort out this issue

**Comment by gaoyang189** [comment]
Bluetooth USES Buttonless Secure DFU

**Comment by gaoyang189** [comment]
Bluetooth USES Buttonless Secure DFU

**Comment by RRMoelker** [comment]
What was your solution?
